name: scrobblenaut
description: A deadly simple LastFM API Wrapper for Dart. So deadly simple that it's gonna hit the mark.
version: 3.0.0
homepage: https://github.com/Nebulino/Scrobblenaut
issue_tracker: https://github.com/Nebulino/Scrobblenaut/issues

environment:
  sdk: ">=2.12.0-0 <4.0.0"

dependencies:
  meta: ^1.9.0
  json_annotation: ^4.8.1
  convert: ^3.1.1
  dio: ^5.3.3
  crypto: ^3.0.3
  xml: ^6.2.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
